### ISSUE TITLE
install fails with undefined method `parse' for Utils::JSON:Module

### ISSUE THREAD

**Issue by TheJefe** [theory/homebrew-sqitch#30]
```
brew install sqitch
==> Installing sqitch from theory/sqitch
==> Installing dependencies for theory/sqitch/sqitch: sqitch_dependencies
==> Installing theory/sqitch/sqitch dependency: sqitch_dependencies
==> Downloading http://api.metacpan.org/source/DWHEELER/App-Sqitch-0.9995/META.json
Already downloaded: /Users/jkoenig/Library/Caches/Homebrew/sqitch_dependencies-0.9995.json
Error: undefined method `parse' for Utils::JSON:Module
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/theory/homebrew-sqitch/Formula/sqitch_dependencies.rb:20:in `block in install'
/usr/local/Homebrew/Library/Taps/theory/homebrew-sqitch/Formula/sqitch_dependencies.rb:19:in `open'
/usr/local/Homebrew/Library/Taps/theory/homebrew-sqitch/Formula/sqitch_dependencies.rb:19:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:137:in `block in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1139:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1934:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:98:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:94:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:86:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1921:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1134:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

I am using OSX 10.12.1

**Comment by theory** [comment]
Any ideas, @andreabedini?

**Comment by theory** [comment]
Bah, sorry @andreabedini, just saw #31. Please ignore me.
